# Club World Cup Constants
LEAGUES_OF_INTEREST = [15, 1168]  # FIFA Club World Cup, Intercontinental Cup
SEASONS = list(range(2000, 2024))

# Continent Mapping
CONTINENT_MAPPING = {
    "North America": "North & Central America",
    "Central America": "North & Central America",
    "North and Central America": "North & Central America",
    "Europe": "Europe",
    "South America": "South America",
    "Asia": "Asia",
    "Africa": "Africa",
    "Oceania": "Oceania",
}

# Club Name Mapping
TEAM_MAPPING = {
    # Clubes árabes
    "Al-Ahli": "Al Ahly",
    "Al Ahly": "Al Ahly",
    "Al Hilal": "Al Hilal",
    "Al-Hilal Saudi FC": "Al Hilal",
    "Al-Ittihad FC": "Al-Ittihad",
    "Al-Ittihad": "Al-Ittihad",
    "Al-Jazira": "Al-Jazira",
    "Al-Wahda": "Al-Wahda",
    "Al-Duhail SC": "Al-Duhail",
    "Al-Sadd": "Al Sadd",
    "Al Nassr": "Al Nassr",
    "Al-Ain": "Al-Ain",
    "Al Ain": "Al-Ain",
    # Clubes africanos
    "Espérance de Tunis": "Espérance de Tunis",
    "Esperance Tunis": "Espérance de Tunis",
    "Wydad Casablanca": "Wydad Casablanca",
    "Mamelodi Sundowns": "Mamelodi Sundowns",
    "TP Mazembe": "TP Mazembe",
    "Étoile du Sahel": "Étoile du Sahel",
    "Moghreb Tetouan": "Moghreb Tétouan",
    "AS Pirae": "AS Pirae",
    "Raja Casablanca": "Raja Casablanca",
    # Clubes asiáticos
    "Urawa": "Urawa Red Diamonds",
    "Urawa Red Diamonds": "Urawa Red Diamonds",
    "Ulsan HD": "Ulsan Hyundai",
    "Ulsan Hyundai FC": "Ulsan Hyundai",
    "Ulsan Hyundai": "Ulsan Hyundai",
    "Jeonbuk Motors": "Jeonbuk Hyundai Motors",
    "Jeonbuk Hyundai Motors": "Jeonbuk Hyundai Motors",
    "Kashima": "Kashima Antlers",
    "Kashima Antlers": "Kashima Antlers",
    "Kashiwa Reysol": "Kashiwa Reysol",
    "Gamba Osaka": "Gamba Osaka",
    "Seongnam Ilhwa Chunma": "Seongnam Ilhwa Chunma",
    "Sanfrecce Hiroshima": "Sanfrecce Hiroshima",
    "Sepahan": "Sepahan",
    # América do Norte
    "Monterrey": "Monterrey",
    "Pachuca": "Pachuca",
    "América": "Club America",
    "Club America": "Club America",
    "Guadalajara": "Guadalajara",
    "Necaxa": "Necaxa",
    "Seattle Sounders": "Seattle Sounders",
    "Atlante": "Atlante",
    "Leon": "León",
    "Cruz Azul": "Cruz Azul",
    "Toronto FC": "Toronto FC",
    # América do Sul
    "Palmeiras": "Palmeiras",
    "Flamengo": "Flamengo",
    "Fluminense": "Fluminense",
    "Botafogo": "Botafogo",
    "São Paulo": "São Paulo",
    "Internacional": "Internacional",
    "Gremio": "Grêmio",
    "Grêmio": "Grêmio",
    "River Plate": "River Plate",
    "Boca Juniors": "Boca Juniors",
    "Atlético-MG": "Atlético-MG",
    "Atletico-MG": "Atlético-MG",
    "Atletico Nacional": "Atlético Nacional",
    "LDU Quito": "LDU Quito",
    "Estudiantes": "Estudiantes",
    "Deportivo Saprissa": "Deportivo Saprissa",
    # Europa
    "Bayern de Munique": "Bayern Munich",
    "Bayern Munich": "Bayern Munich",
    "Red Bull Salzburg": "Red Bull Salzburg",
    "Benfica": "Benfica",
    "FC Porto": "Porto",
    "Porto": "Porto",
    "Chelsea": "Chelsea",
    "Manchester City": "Manchester City",
    "Manchester United": "Manchester United",
    "Real Madrid": "Real Madrid",
    "Atlético de Madrid": "Atlético de Madrid",
    "Borussia Dortmund": "Borussia Dortmund",
    "Juventus": "Juventus",
    "Inter de Milão": "Inter Milan",
    "Internazionale": "Inter Milan",
    "Liverpool": "Liverpool",
    "Barcelona": "Barcelona",
    "Paris Saint-Germain": "Paris Saint-Germain",
    "Milan": "AC Milan",
    # Oceania
    "Auckland City": "Auckland City",
    "Waitakere United": "Waitakere United",
    "Hekari United": "Hekari United",
    "Hienghène Sport": "Hienghène Sport",
    "South Melbourne": "South Melbourne",
    "Sydney FC": "Sydney FC",
    "Western Sydney Wanderers": "Western Sydney Wanderers",
    "Team Wellington": "Team Wellington",
    # Correções extras para garantir consistência
    "Wydad AC": "Wydad Casablanca",
    "Étoile Sportive du Sahel": "Étoile du Sahel",
}

TEAM_MAPPING_LOWER = {
    "al-ahli": "al ahly",
    "al ahly": "al ahly",
    "al hilal": "al hilal",
    "al-hilal saudi fc": "al hilal",
    "al-ittihad fc": "al-ittihad",
    "al-ittihad": "al-ittihad",
    "al-jazira": "al-jazira",
    "al-wahda": "al-wahda",
    "al-duhail sc": "al-duhail",
    "al-sadd": "al sadd",
    "al nassr": "al nassr",
    "al-ain": "al-ain",
    "al ain": "al-ain",
    "espérance de tunis": "espérance de tunis",
    "esperance tunis": "espérance de tunis",
    "wydad casablanca": "wydad casablanca",
    "mamelodi sundowns": "mamelodi sundowns",
    "tp mazembe": "tp mazembe",
    "étoile du sahel": "étoile du sahel",
    "mogheb tetouan": "mogheb tétouan",
    "as pirae": "as pirae",
    "raja casablanca": "raja casablanca",
    "urawa": "urawa red diamonds",
    "urawa red diamonds": "urawa red diamonds",
    "ulsan hd": "ulsan hyundai",
    "ulsan hyundai fc": "ulsan hyundai",
    "ulsan hyundai": "ulsan hyundai",
    "jeonbuk motors": "jeonbuk hyundai motors",
    "jeonbuk hyundai motors": "jeonbuk hyundai motors",
    "kashima": "kashima antlers",
    "kashima antlers": "kashima antlers",
    "kashiwa reysol": "kashiwa reysol",
    "gamba osaka": "gamba osaka",
    "seongnam ilhwa chunma": "seongnam ilhwa chunma",
    "sanfrecce hiroshima": "sanfrecce hiroshima",
    "sepahan": "sepahan",
    "monterrey": "monterrey",
    "pachuca": "pachuca",
    "américa": "club america",
    "club america": "club america",
    "guadalajara": "guadalajara",
    "necaxa": "necaxa",
    "seattle sounders": "seattle sounders",
    "atlante": "atlante",
    "leon": "león",
    "cruz azul": "cruz azul",
    "toronto fc": "toronto fc",
    "palmeiras": "palmeiras",
    "flamengo": "flamengo",
    "fluminense": "fluminense",
    "botafogo": "botafogo",
    "são paulo": "são paulo",
    "internacional": "internacional",
    "gremio": "grêmio",
    "grêmio": "grêmio",
    "river plate": "river plate",
    "boca juniors": "boca juniors",
    "atlético-mg": "atlético-mg",
    "atletico-mg": "atlético-mg",
    "atletico nacional": "atlético nacional",
    "ldu quito": "ldu quito",
    "estudiantes": "estudiantes",
    "deportivo saprissa": "deportivo saprissa",
    "bayern de munique": "bayern munich",
    "bayern munich": "bayern munich",
    "red bull salzburg": "red bull salzburg",
    "benfica": "benfica",
    "fc porto": "porto",
    "porto": "porto",
    "chelsea": "chelsea",
    "manchester city": "manchester city",
    "manchester united": "manchester united",
    "real madrid": "real madrid",
    "atlético de madrid": "atlético de madrid",
    "borussia dortmund": "borussia dortmund",
    "juventus": "juventus",
    "inter de milão": "inter milan",
    "internazionale": "inter milan",
    "liverpool": "liverpool",
    "barcelona": "barcelona",
    "paris saint-germain": "paris saint-germain",
    "milan": "ac milan",
    "auckland city": "auckland city",
    "waitakere united": "waitakere united",
    "hekari united": "hekari united",
    "hienghène sport": "hienghène sport",
    "south melbourne": "south melbourne",
    "sydney fc": "sydney fc",
    "western sydney wanderers": "western sydney wanderers",
    "team wellington": "team wellington",
    "wydad ac": "wydad casablanca",
    "étoile sportive du sahel": "étoile du sahel",
}

# Country Mapping
COUNTRY_MAPPING = {
    "New-Caledonia": "New Caledonia",
    "New-Zealand": "New Zealand",
    "Papua New Guinea": "Papua New Guinea",
    "Saudi-Arabia": "Saudi Arabia",
    "South-Africa": "South Africa",
    "South-Korea": "South Korea",
    "United-Arab-Emirates": "UAE",
    "United Arab Emirates": "UAE",
    "USA": "United States",
}
